# Generated by Django 5.2.6 on 2025-09-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='razorpay_order_id',
            new_name='stripe_subscription_id',
        ),
    ]
