# Generated by Django 5.2.6 on 2025-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0003_subscription_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
