# Generated by Django 5.2.6 on 2025-09-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0005_alter_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
